name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sncf-on-time

    - uses: 'actions/checkout@v3'
    - name: Tag the docker image
      run: docker tag sncf-on-time europe-west9-docker.pkg.dev/ensai-2023-373710/francois-depot/sncf-on-time

    - name: Auth on GCP
      uses: docker/login-action@v2
      with:
        registry: europe-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Push the docker image
      run: docker push europe-west9-docker.pkg.dev/ensai-2023-373710/francois-depot/sncf-on-time